### ISSUE TITLE
Number of tests is wrong

### ISSUE THREAD

**Issue by simonwistow** [fastly/fastly-perl#1]
> Fails the tests with:
> 
> Building and testing Net-Fastly-0.7
> Building Net-Fastly
> t/admin.t ......... ok
> # Looks like you planned 96 tests but ran 95.
> 
> t/api_key.t .......
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 1/96 subtests
>        (less 95 skipped subtests: 0 okay)

**Comment by Integralist** [comment]
Closing this issue now we've published 2.01.
