### ISSUE TITLE
Soft purge support

### ISSUE THREAD

**Issue by ranguard** [fastly/fastly-perl#16]
Please could you add support for soft purge, or at least setting headers.

Something like:

```perl
purge($url, { 'Fastly-Soft-Purge' => 1 } );
```

Would be enough

**Comment by simonwistow** [comment]
@ranguard can you give this a test and see if it works for you?

**Comment by ranguard** [comment]
Code looks good, sorry I don't really have a testing setup I can easily use for testing this (it's on our todo list!)

**Comment by ranguard** [comment]
Merged in - so closing - thanks
