### ISSUE TITLE
Needs a release

### ISSUE THREAD

**Issue by ranguard** [fastly/fastly-perl#22]
@simonwistow @miyagawa @acme 

https://github.com/fastly/fastly-perl/pull/20 was merged on the 20th of Jan.

Please could someone release to CPAN (I don't need the refactor, just this released) I had a support ticket open for this as well, but it was closed as this was meant to be being progressed shortly

Thanks

Leo

**Comment by simonwistow** [comment]
Released as v1.04 to cpan

**Comment by ranguard** [comment]
Wonderful - thank you
